name: Use a hosted action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate PR Codename
        uses: a-magdy/pr-codename-generator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
