name: Use a hosted action

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Generate PR Codename
        uses: a-magdy/pr-codename-generator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
